# <center> Chapter 1: Introduction to Python </center>

## Learning objectives
After processing this chapter you will be able to

>-   work with the Python graphical user interface
>-   perform basic calculations with numbers, vectors and matrices
>-   write and execute script files in any directory


## Getting to know your tools

The aim of this course is to familiarize the reader with the basic
concepts in programming in general. Programming skills are very helpful
for scientific research and have to be employed when programming
measurement equipment, data analysis routines or simulations.

In the case you are already familiar and experienced in programming, this
course will not offer many new things. On the
other hand, we tried to use examples and exercises from the field of
renewable energies which still might be of interest to you. So we
suggest that you could read the examples and
exercises and make sure that you perfectly understand them.

There exists a large number of programming languages. In recent years the Python programming language has become
more and more popular in the scientific community due to its very active
community which develops and shares many useful library of codes as well
the fact that (as for example compared to MATLAB) it is free.

There exists large amounts of tutorials and literature on Python and
many are admittedly of much higher quality and scope as this course.
This course will focus on what we feel is the most important and aims to
provide motivational examples from Renewable Energies.

## Programming Languages

Computers or computing devices make use of sets of grammatical rules or
instructions to perform specific tasks and generate desired outputs.
These systematically defined set of instructions fed into the computer
are known as programming languages. Over the years, programming
languages have found its application from basic numerical computations
to web app developments, data analysis, simulations, artificial
intelligence etc.

Programming languages differ in their abstraction level from the machine
level. They are roughly categorized as (see also [Wikipedia (PGL)](https://en.wikipedia.org/wiki/Programming_language_generations)):

   **1st generation:**  machine languages direct instructions of the processor (only 0s and 1s) non-intuitive to read or write
   
   **2nd generation:**  assembly languages use labels and names of human languages, commands relate to single instructions
   
   **3rd generation:**  higher, general languages use commands in the logical structure of human languages (example C), one command may correspond to multiple processor instructions
   
   **4th generation:**  higher, specialist languages abstracts the general commands to more field specific languages, provides libraries and constructs typical of the specialization field, can be machine independent by using run-time environments
   
   **5th generation:**  solve problems without a programmer


Though generations of programming languages differ in structure and
semantics, high-level programming languages are similar in structure and
knowledge if one can aid the understanding of another.

## The python programming language

The python programming language was created by Guido van Rossum in the
late 1980s. Python has a wide range of applications ranging from web
development, scientific and mathematical computing to desktop user
interfaces Over the years, Python has gained enormous popularity among
programmers due to the following reasons (reference: [Programiz](https://www.programiz.com/python-programming)):

-   It is a multi-purpose programming language with very simple syntax,
    thereby making it easier to write and read python programs and a
    good start point for inexperienced programmers

-   Python is free and open- source with a large community of
    programmers constantly improving its features and application.
    Python codes are also very portable between platforms like Windows,
    Mac OS X and Linux

-   Python is extensible and embeddable given that it can be combined
    with languages such as C/C++ for high performance applications.

-   It is a high level, interpreted language removing the challenges
    associated with memory management, garbage collection etc. as found
    in C/C++Variable type definition are also not applicable given that
    it automatically understands the variable input.

-   Being an object-oriented programming language, complex problems can
    be divided into smaller units by object creation in python allowing
    for intuitive solution to complex problems.

-   Python has several standard libraries that minimizes the amount of
    code needed to execute a task and makes programming easier. For
    instance, MYSQL database can be connected to a server simply by
    importing a standard library MySQLdb

Python has numerous applications. Python frameworks such as Django,
Flask, Pyramid etc., and Content Management System (CMS) can be used to
build scalable web applications. Python has several libraries such as
SciPy, NumPy that can be used for scientific and numerical computing
which are especially important for our applications. Specific libraries
such as EarthPy and AstroPy are useful for earth science and astronomy
respectively. Python packages such as matplotlib and Pandas are
important for data visualization and analysis. Given the easy syntax of
python, it can be used to create software prototypes such as games in
which the actual game can be built using C++ upon prototype validation.

### Getting started with Python in JupyterLab

We use two different types of cells in JupyterLab in this course: Markdown and Code. If you double click on the content you are reading right now, you can check the text written in [Markdown](https://de.wikipedia.org/wiki/Markdown) format. You can edit the contents and press <kbd>shift</kbd> + <kbd>enter</kbd> to run the changes. You select Code (from the upper bar) for cells in which you will add Python code for execution as the below cell. 

In [2]:
8+8

16

It is recommended to check this [link](https://jupyterlab.readthedocs.io/en/stable/user/interface.html) for more detailed overview of the JupyterLab interface and functionality.

#### Basic Calculations

Numerical operations on basic numbers are performed with the following
operators:

``` python
+, -, *, /
```

The operations are processed in the standard method known from
mathematics, i.e. first multiplication/divisions, secondly
addition/subtraction. In order to force that an operation is processed
out of this order use parantheses.

``` python
(  )
```

To calculate powers of numbers employ the operator:

``` python
**
```

💡 ><font color=red>Feel free to change the contents in the below cell and try different operations.</font>

In [19]:
(8**2 + 6)/7

10.0

### Scripting a Python Code

Of course we usually compose multiple lines of code (for which we use
the editor) and which are saved as script files.

There are a few things to note while writing a python script:

-   Python does what ever you want it to do once your codes are free of
    errors

-   Python executes the written code sequentially (line by line). It is
    important that your code is well structured in an organized flow
    path

-   When you have more than one statement on a line, then a semicolon is
    used to separate them. Writing two statements in one line is however
    considered a bad way of programming

-   Variable names are case sensitive in python. **print** and **Print**
    are two different commands to python.

In [20]:
print('Hello World!')

Hello World!


In [21]:
Print('Hello World!')

NameError: name 'Print' is not defined

### Comments and Doc Strings

Comments are useful in giving proper explanation of the written code in
python. Anything written after the \# character is comment and ignored
by python during code execution. Proper commenting of codes aids its
readability and understanding. Comments can be single line comment such
as:

In [24]:
#This is a single line comment.  

or inline comment with code such as:

In [23]:
print("Hi There!!") #This code prints: Hi There!!

Hi There!!


Documentation strings are like comments but applied at the beginning of
a module, class, method or function. They can be accessed and viewed
programmatically using `help(obj_name)`, and in IPython
by applying a question mark `?` at the end of the module, class or
function name.

In [3]:
def Celsius_2_Fahrenheit_conv():
    """
    This is a function that takes the temperature value in degree Celsius and returns its equivalent in Fahrenheit
    """
    temp = float(input("Please enter the temperature value in Celsius degree:")) # Asks the user for temperature value and stores it in a variable temp
    Fahrenheit = 9/5*temp + 32 # Uses the formula to calculate the fahrenheit equivalent
    return Fahrenheit

In the above example the words enclosed in the three inverted comas
\"\"\" are known as documentation strings and simply typing
`help(Celsius_2_Fahrenheit_conv)` or `Celsius_2_Fahrenheit_conv?` will display the documentation
for the code on the IPython Console. Further information on doc strings
can be found [here](https://www.python.org/dev/peps/pep-0257/).

When your command line window becomes too full you can use `clear` to
empty it.

## Data types

##### Primitive data types

On the most basic level all data in a computer is stored and processed
in the binary format which can be represented as a sequence of 0's and
1's. Given an arbitrary binary sequence such as for example 00100110
therefore does not have any meaning in itself.

Only when we know how the meaning of the sequence we can interpret it as
for instance a part of an mp3 file, an image or a text. Therefore we
have to provide to each data that we are using a *data type* in order to
decode its meaning.

That means also that the same binary sequence can have different
meanings depending on its interpretation. For example if we interprete
the binary sequence as a positive integer it is interpreted as 38. Yet,
if we interprete said sequence as an ASCII character (that is a
standardized look-up table for typographic symbols, see for example
[this reference](http://www.ascii-code.com/)) the binary sequence corresponds to the ampersand
character &.

| binary     | integer  | ASCII character |
|:----------:|:--------:|:---------------:|
| 00100110   | 38       | &               |

Beside these two interpretations there exist a few other primitive data
types which are used in programming. Notice, that different data types
require binary sequences of different (but usually standardized) length.

In the table below we name just a few data types to give you an idea
what you are working with.

| Datatype   | Notes                                                   |
|:----------:|:-------------------------------------------------------:|
| Integer    | positive or negative integer                            |
| Float      | positive/negative number of the type: +0.12345e+10      |
| Double     | same as float with double precision (twice as many bits)|
| Character  | ASCII character                                         |

Python support both numeric and non-numeric data types. A complete
overview on in-built data types in python can be found [here](https://docs.python.org/3/library/stdtypes.html).
Here we want to give a little bit more detail about the most important
data types. The `type` function in python is useful to evaluate the
datatype or class of any value.

#### Integers

Integers are whole numbers i.e. they have non fractional parts and can
be positive, negative or zero. 8, -15, 1500 are examples of integers.
Python supports a lot of operations such as addition, subtraction,
multiplication etc., on integers. The range of integers that can be
handled by Python depends on the size (number of bits) of the reserved
storage location. For example with an 8bit storage location you can only
manage $2^8$ different integers which for unsigned integers only
corresponds to the range 0\...255.

#### Float

Many numerical computations involve numbers having fractional parts.
Such non-integer numbers such as 4.0, -0.09, 3.142 etc. are referred to
as floating point numbers since the decimal point can move or 'float' to
various positions within the number to maintain proper number of
significant digits during mathematical calculations. Python supports the
same numerical operations as in integers on floats. Floating point
values are usually approximations of real numbers having limited range
since each value must be stored in a fixed amount of memory. For
instance, $\pi$ is an irrational number that contains several digits in
a non-uniform repeating pattern. Such values can only be approximated
using the range of memory available for such data types.

The object `sys.float_info` contains information on memories that
floats occupy. Float values up to 1.7976931348623157e+308 and
2.2250738585072014e-308 can be stored and processed by the computer.
Values beyond these ranges will be truncated. In python 2, integer
division truncates. This meant that evaluating 4/5 yields 0 as output
since Python evaluates it as an integer division; thereby returning the
least whole number which is 0. However, this has been corrected in
python 3. The functions `float(n)` and `int(n)` can be used to convert
any datatype to float and integer respectively.

In [16]:
import sys

In [17]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [9]:
a = 9/2
print(a)

4.5


In [10]:
type(a)

float

In [13]:
int(a)

4

However, it is important to note that variable 'a' still has the same value and type.

💡 ><font color=red>Insert a cell below and check for yourself</font>

#### Complex numbers

Python provides a special datatype for complex numbers. If you type
a=1+3j you will see in the variable manager that a new variable of the
type complex appears.

In [1]:
type(1+3j)

complex

#### Arrays

An array is a data structure that can hold values of same data type. It
could be a one, two- or n-dimensional array. A one dimensional array
would correspond a vector while a 2-dimensional array would correspond
to a matrix. To use arrays in python, you need to import the array
module using the `import` command

``` python
from array import *  # Imports the array module in python
```

Having imported the array module, an array can be declared as follows:

``` python
arrayIdentifierName = array(typecode, [Initializers]) 
```

ArrayIdentifierName represents the name of the array, typecode lets
python know the data type in the array while initializers are the values
with which array is initialized. Common typecodes include:

| Typecode | Details                                     |
|:--------:|:-------------------------------------------:|
| i        | Represents signed integers of size 2 bytes  |
| I        | Represents unsigned integer of size 2 bytes |
| c        | Represents character of size 1 byte         |
| f        | Represents floating point of size 4 bytes   |
| d        | Represents floating point of size 8 bytes   |
| b        | Represents signed integer of size 1 byte    |
| B        | Represents unsigned integer of size 1 byte  |

The example below shows an array creation with some array executable
operations

In [1]:
from array import *  # Imports  the array module in python

In [2]:
array_1 = array("i", [2,4,6,8,10]) # Creates an array of integer values named array_1

In [3]:
array_1

array('i', [2, 4, 6, 8, 10])

In [4]:
array_1.append(12)                 # Adds 12 to array_1.

In [5]:
array_1

array('i', [2, 4, 6, 8, 10, 12])

In [6]:
array_2 = array("i", [1, 3,5,7,9]) # Creates another integer array named array_2.

In [7]:
array_2

array('i', [1, 3, 5, 7, 9])

In [8]:
array_1.extend(array_2)            # Joins the contents of array_2 to array_1

In [9]:
array_1

array('i', [2, 4, 6, 8, 10, 12, 1, 3, 5, 7, 9])

In [10]:
array_1.remove(7)                  # Removes 7 from array_1

In [11]:
array_1

array('i', [2, 4, 6, 8, 10, 12, 1, 3, 5, 9])

In [35]:
array_1.reverse()                  # Reverses the contents of array_1

In [36]:
array_1

array('i', [9, 5, 3, 1, 12, 10, 8, 6, 4, 2])

In [53]:
type(array_1)

array.array

Further documentation on n-dimensional arrays and possible operations on
such arrays can be found [here](https://docs.python.org/2/library/array.html). An efficient and more convenient
way of handling arrays is using the NumPy arrays. The NumPy module and
its usage in python will be discussed in the following sections.

#### Strings

In a table above we have introduced a 'character' (e.g. from the ASCII
table) as a datatype. Strings are basically arrays of characters and
they are important as they represent a way to communicate with the user
for example through written language. Because they are so important they
are usually treated a little different from arrays to distinguish them.

A string in Python can consist of letters or numbers or a combination of
both. They should always be enclosed with either single ' ' or double
\"\" quotation marks. It is important that strings started with one or
double quotation mark must be closed with one or double quotation marks
respectively. Mind that a numbers in a string are NOT representations of
the numerical value but rather just the character representing the
numerical value. As example: While 8 is an integer value and 8.7578 is a
float value, \"8\" or '8.7578' is no longer an integer resp. float but a
string.
The statement `print(8)` prints integer value 8 on the IPython Console.

Strings are immutable, indexable and iterable. Given that strings are
sequences of characters, they are indexable with the index starting from
zero and increasing upwards

<center><img src="img/01_python/stringsindexing.jpg"/></center>
<center>Figure 1.2: Indexing of Strings. (Source: Author)</center>

In [80]:
greeting = 'Hi There!'

In [81]:
greeting[4]

'h'

### Python Libraries and Packages

Python employs a lot of libraries and packages for numerous applications
such as data science, machine learning, statistics, as well as Web
development and desktop application. Libraries are files which contain
many functions so that you don't have to programm everything from
scratch. For example basic Python does provide the multiplication
operator which is applicable for integers and floats but it does not
provide a function which performs the dot product between vectors. In
order to use a dot product you would either have to programm it yourself
or (recommended) find a library which contains this function already.

Commonly used libraries for data analysis include: 

**Pandas:** [Pandas](https://pandas.pydata.org/) is
a very important and powerful library for data manipulation in Python.
It has a broad range of import and export functions for various data
formats such as Comma separated variable (CSV) and text files, Microsoft
Excel, SQL databases,etc, as well as indexing and data manipulating
capabilities. Pandas also contains well developed methods for data
structures such as dataframe, which is a table of columns and rows of
data. Pandas mostly used to merge, reshape, split, aggregate and
select(sub-setting) data. It is usually customary to import pandas as
`pd` inside the python code. 

[//]: # "it will not be included Further documentation on Pandas can be
found in ref, this was removed from the original script since the ref hypperlink is included in the first line"


**NumPy (Numerical Python):** [NumPy](http://www.numpy.org/) is an efficient
library for Numerical operations and data storage in python. It has data
structures, algorithms and functions used for handling numerical data in
Python.NumPy contains data structures, algorithms and high-level
mathematical functions that support large, multi-dimensional arrays and
matrices operations.In addition, Numpy is efficient in generating and
handling data that are either normally or binomially distributed. NumPy
is usually imported as `np`. 

**Matplotlib:** [Matplotlib](https://matplotlib.org/) is a very powerful library for
data visualization in 2D or 3D in Python. The pyplot module in
Matplotlib allows for a lot of control over plots such as graphs, bar
charts, pie charts, histograms etc. `import matplotlib.pyplot as plt`
imports the pyplot module in matplotlib for various forms of data
visualization. 

**SciPy:** The [SciPy](https://www.scipy.org/scipylib/index.html) library contains user-friendly and
efficient modules used for linear algebra, optimization, integration,
interpolation, FFT, signal and image processing, ODE and PDE solvers and
other numerical routines that are common in science and Engineering.

Whenever we want to use a function from a library we state the library
name, then a dot and then the function name so that Python knows where
to look. For example: `numpy.cos()`. It is common to abbreviate the
library names to make the code shorter and better readable. This can be
achieved by specifying an alternative name which is realised by
exptending the import command with as 'alternative name'


## Script files

Until now we typed all the commands directly into the command line. As
it would be very tedious to type each command individually into the
command line we can store multiple commands in scripts. These scripts
can be created using the built-in editor of the programming environment.

From the editor element you can run your script file directly by
clicking the green 'Play' button.

Make sure to save the script and give it a meaningful name. Notice that
script files must have the document type ending '.py'.

You can also run the script file from the command line. For this type
`run [filename]`. However, in order for Python to call a script it must
be in a 'visible' folder. That will always be the case if the script
file is in the active working directory.

> **Example 1.1 - Airmass script** 
<br>
> The intensity of the sun felt on the surface of the earth is influenced
by the atmosphere. Depending on the position of the sun relative to your
position on earth the solar radiation has to pass more or less distance
of the atmosphere.
<br>
> This is expressed in the quantity called airmass where a value of
airmass AM=1 corresponds to the shortest possible distance the solar
radiation has to travel when the sun is directly overhead (in the
so-called zenith). According to [PVEducation (Air mass)](https://www.pveducation.org/pvcdrom/properties-of-sunlight/air-mass) the airmass
factor for angles $\alpha$ from the zenith is given by
> $$AM=\frac{1}{\cos(\alpha)}$$
> Let's write a script to calculate the airmass for an angle
> $\alpha=30^{\circ}$
<br>
> *01airmassscript.py*

In [1]:
import numpy as np 
  
#Parameter
AngleFromZenith = 30; #in degrees
AngleFromZenith_Rad = np.deg2rad(AngleFromZenith);   #convert from degrees to radians

#Calculations
AM = 1/np.cos(AngleFromZenith_Rad);
print(AM);

1.1547005383792515


There is a lot we can learn from this example. In the first line we
import the NumPy library which provides us with mathematical functions
such as the cosine function and define that we want to abbreviate this
library with just 'np'.

By default in most programming languages the trigonometric functions are
programmed to handle angles in terms of radians and not degrees.
Therefore we have to transform our angle in degrees into radians using
the deg2rad function from the NumPy library.

Finally we perform the calculation and output the result to the command
line.

## Useful functions to get you started quick

Other numeric constructs which are very common in scientific computing
are vectors and matrices. Let's start with the vectors.

With NumPy you can implement a vector via: `a=np.array([1,2,3])`. With
arrays of the **same size** you can perform arithmetic operations which
will work elementwise. For example: a+a outputs an array \[2,4,6\]

In [42]:
a = np.array([1,2,3])

In [43]:
a

array([1, 2, 3])

In [41]:
a + a

array([2, 4, 6])

Before we stated that one-dimensional arrays can be imagined as a
vector. That is not entirely correct as we often distinguish between row
and column vectors which is important for example for dot or matrix
products.. These are represented more correctly by a 2-dimensional array
where one dimension is equal to 1.

In [44]:
v = np.r_['r', [1,2,3]]     # shape: (1, 3)

In [45]:
v

matrix([[1, 2, 3]])

In [46]:
w = np.r_['c', [4,5,6]]  # shape: (3,1)

In [47]:
w

matrix([[4],
        [5],
        [6]])

To transpose a row vector into a column vector (or vice versa) use the
`transpose()` function.

In the case you want to address not the complete vector but just one
element of it write:

In [48]:
a[2]

3

You may be surprised about this result as you may have expected this to
output a 2 instead. In most programming languages it is common to start
counting with 0 so in this case a\[0\]=1,\... This is called indexing.

For matrixes and the special variant of row and column vectors you need
to provide 2 indices, one for the row (1st number) and one for the
column (2nd number).

In [49]:
w[1,0]

5

We can construct matrices as array of arrays (mind that the row arrays
are nested within \[\]:

In [50]:
C=np.array([[1,2,3],[4,5,6]])

In [51]:
C

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
type(C)

numpy.ndarray

As mentioned before you can perform element wise operations using the
regular arithmetic operators

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [5]:
print(A)

[[1 2]
 [3 4]]


In [6]:
print(B)

[[5 6]
 [7 8]]


In [30]:
print(A+B)

[[ 6  8]
 [10 12]]


In [58]:
print(A*B)

[[ 5 12]
 [21 32]]


In the case you want to add a scalar value to all elements you can use
special operators such as `+=` or for multiplication `*=`.

In [31]:
A+=5

In [32]:
print(A)

[[6 7]
 [8 9]]


To perform a 'proper' matrix multiplication (not elementwise), dot product and cross multiplication can be done using the np.dot and np.cross functions respectively.

In [35]:
print(np.dot(A,B))

[[ 79  92]
 [103 120]]


In [20]:
C = np.array([[2,1,-3]])
print(C)

[[ 2  1 -3]]


In [25]:
np.shape(C) #check that array shape is correct

(1, 3)

In [22]:
D = np.array([[0,4,5]])
print(D)

[[0 4 5]]


In [23]:
print(np.cross(C,D))

[[ 17 -10   8]]


Of course there exist many more functions for matrices and vectors but
this shall be enough to get you started. Always remember, if you are
looking for something but don't know if there exists a function for it
first google it and use the documentation.

### Debugging: Getting rid of errors in Python

Many types of errors such as SyntaxError, ImportError, IndexError,
KeyError, RuntimeError, UnicodeEncodeError etc. can occur during code
execution. Python documentation on errors can be found [here](https://docs.python.org/3.4/library/exceptions.html). A
common approach to resolving python errors is to copy and paste the
error message on Google, as [StackOverflow](https://stackoverflow.com/) provides a large
community of Programmers who have probably encountered a similar error
in the past (highly recommended!).

Try to understand what is happening in the following example. In the
following chapter we will built upon this. Feel free to play around with
it for different results.

> **Example 1.2 - Sun Postion**
<br>
The sun is the original power source of many renewable energies. In
order to describe our energy resource it is therefore often necessary to
determine the position of the sun.
<br>
The apparent position of the sun can be given by two angles, the
elevation and the azimuth. [PVEducation (Sun position)](https://www.pveducation.org/pvcdrom/properties-of-sunlight/the-suns-position) details how
to calculate these two angles as a function of time and gives the
following equations. $$\begin{aligned}
    LSTM&=15^{\circ} \times \Delta T_{GMT} \\
    B&=\frac{360}{365}(d-81) \\
    EoT&=9.87\sin(2B)-7.53\cos(B)-1.5\sin(B) \\
    TC&=4(\lambda-LSTM)+EoT\\
    LST&=LT+\frac{TC}{60}\\
    HRA&=15^{\circ} (LST-12)\\
    \text{Declination } \delta&=\sin^{-1} \left( \sin (23.45^{\circ} ) \sin \left(   \frac{360}{365}(d-81) \right)\right)\\
    \text{Elevation } \alpha&=\sin^{-1} \left( \sin \delta \sin \varphi + \cos \delta \cos \varphi \cos(HRA)  \right)\\
    \text{Azimuth } \psi &=\cos^{-1} \left( \frac{\sin \delta \cos \varphi - \cos \delta \sin \varphi \cos(HRA) }{\cos \alpha} \right)\\\end{aligned}$$
    <br>
These equations shall be implemented in Python for the specific set of
parameters: $$\begin{aligned}
    LT&=15:30\\ 
    d&=309 \text{ (Nov 5th)}\\
    \Delta T_{GMT}&=+2 \text{ (CET)}\\
    \text{Longitude } \lambda&=8.213889\\
    \text{Latitude } \varphi&=53.143889\\\end{aligned}$$
<br>
*02sunposscript.py*

In [1]:
import numpy as np

#Initial Parameters
DayOfYear=309 #Nov 5th in the year 2015
TimeZone=+2 #Difference to Greenwich Mean Time GMT
SummerTime=0 #1=TRUE, 0=FALSE
Longitude=8.213889  #Oldenburg (in degrees)
Latitude=53.143889 #Oldenburg (in degrees)
EarthTilt=23.45 #degrees

#Translate degree values into radians
Long_rad=np.deg2rad(Longitude)  
Lat_rad=np.deg2rad(Latitude) 
Tilt_rad=np.deg2rad(EarthTilt) 

LT=15.5 #afternoon would correspond to 3:30 pm
LSTM=15*(TimeZone+SummerTime)
B=(360/365)*(DayOfYear-81) #Postition on the orbit (angle)
EoT = 9.87*np.sin(np.deg2rad(2*B))-7.53*np.cos(np.deg2rad(B))-1.5*np.sin(np.deg2rad(B)) #minutes
TC=4*(Longitude-LSTM)+EoT #in minutes
LST=LT+TC/60
HRA=15*(LST-12) #Hour angle, 0 at noon

Declination_rad = np.arcsin(np.sin(Tilt_rad)*np.sin(np.deg2rad(B)))
Elevation = np.rad2deg(np.arcsin( np.sin(Declination_rad)*np.sin(Lat_rad)+np.cos(Declination_rad)*np.cos(Lat_rad) *np.cos(np.deg2rad(HRA)) ))

Azimuth = np.rad2deg(np.arccos( ( np.sin(Declination_rad)*np.cos(Lat_rad)-np.cos(Declination_rad)*np.sin(Lat_rad) *np.cos(np.deg2rad(HRA)) )/np.cos(np.deg2rad(Elevation)) ))

print('Elevation = ', Elevation)
print('Azimuth = ', Azimuth)

Elevation =  14.368815733077886
Azimuth =  145.58679224984695
